#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : uritemplate
Version  : 0.6
Release  : 3
URL      : https://pypi.python.org/packages/source/u/uritemplate/uritemplate-0.6.tar.gz
Source0  : https://pypi.python.org/packages/source/u/uritemplate/uritemplate-0.6.tar.gz
Summary  : URI Templates
Group    : Development/Tools
License  : Apache-2.0
Requires: uritemplate-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
uritemplate
===========
.. image:: https://secure.travis-ci.org/uri-templates/uritemplate-py.png?branch=master
:alt: build status
:target: http://travis-ci.org/uri-templates/uritemplate-py

%package python
Summary: python components for the uritemplate package.
Group: Default

%description python
python components for the uritemplate package.


%prep
%setup -q -n uritemplate-0.6

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
